name: Publish Rust
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish GH release
        uses: softprops/action-gh-release@v2.1.0
      - name: Publish Crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
